### ISSUE TITLE
Problem: AIP replication not working

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#307]
AIP replication is breaking because `Package.create_replica_pointer_file` is returning `None`, which is caused by `replica_package.should_have_pointer_file()` returning `False` because the replica package is not a file at the time of the call. Sample error log:

    ERROR     2018-01-26 13:15:27  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/file/
    Traceback (most recent call last):
    File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
    File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 451, in dispatch_list
    return self.dispatch('list', request, **kwargs)
    File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch
    response = method(request, **kwargs)
    File "/usr/share/python/archivematica-storage-service/lib/python2.7/site-packages/tastypie/resources.py", line 1380, in post_list
    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))
    File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 572, in obj_create
    premis_agents=agents, aip_subtype=aip_subtype)
    File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 614, in store_aip
    self.create_replicas()
    File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 1266, in create_replicas
    self.replicate(replicator_loc.uuid)
    File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 508, in replicate
    replica_package.full_pointer_file_path)
    File "/usr/lib/archivematica/storage-service/locations/models/package.py", line 2721, in write_pointer_file
    pointer_file.write(pointer_file_path, pretty_print=True)
    AttributeError: 'NoneType' object has no attribute 'write'

Refs https://projects.artefactual.com/issues/10662#note-45.

**Comment by jrwdunham** [comment]
QA should involve testing that AIP replication is in fact now working.

**Comment by sromkey** [comment]
We QA'd this for SFU.
