### ISSUE TITLE
Problem: ``_`` as ``ugettext`` gets overwritten in resources.py

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#329]
See the contradiction in the following two lines:

- https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/api/resources.py#L840
- https://github.com/artefactual/archivematica-storage-service/blob/stable/0.11.x/storage_service/locations/api/resources.py#L881

The last line triggers:

    Traceback (most recent call last):
      File "/usr/share/python/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
        response = callback(request, *args, **kwargs)
      File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 97, in wrapper
        result = func(resource, request, bundle, **kwargs)
      File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 881, in aip_store_callback_request
        "message": _("Failed to POST %(count)d responses to callback URI") % {'count': fail},
    TypeError: 'unicode' object is not callable

Solution: don't use ``_`` as a throw-away variable.

**Comment by jrwdunham** [comment]
Fixed by https://github.com/artefactual/archivematica-storage-service/pull/330#pullrequestreview-97379506

**Comment by jrwdunham** [comment]
I'm moving this to the Done column in the AM 1.7 GH release project because I don't think it needs QA and it definitely doesn't require documentation. This was one of the issues that was breaking the Archidora integration as described in the internal issue at https://projects.artefactual.com/issues/11642. Implementing the fix on the client's machine was part of resolving the overall issue.
