### ISSUE TITLE
Problem: TypeError exception in async module

### ISSUE THREAD

**Issue by sevein** [artefactual/archivematica-storage-service#358]
This code is breaking:

https://github.com/artefactual/archivematica-storage-service/blob/2cc49f7debaeeb77bccb77e99c5844dc41b8b845/storage_service/locations/models/async.py#L34-L36

Traceback:

```
INFO      2018-05-15 17:06:01  locations.models.package:package:store_aip:603:  store_aip called in Package class of SS
INFO      2018-05-15 17:06:01  locations.models.space:space:move_rsync:463:  Moving from /var/archivematica/sharedDirectory/currentlyProcessing/DSpace_transfer_2-7e0bf0ad-d71c-4cc0-a443-71fdae492b65/DSpace_transfer_2-7e0bf0ad-d71c-4cc0-a443-71fdae492b65.7z to /var/archivematica/sharedDirectory/www/AIPsStore/7e0b/f0ad/d71c/4cc0/a443/71fd/ae49/2b65/DSpace_transfer_2-7e0bf0ad-d71c-4cc0-a443-71fdae492b65.7z
INFO      2018-05-15 17:06:02  locations.models.package:package:create_pointer_file:1235:  Pointer file constructed for 7e0bf0ad-d71c-4cc0-a443-71fdae492b65 is valid.
ERROR     2018-05-15 17:06:06  django.request.tastypie:resources:_handle_500:301:  Internal Server Error: /api/v2/async/5/
Traceback (most recent call last):
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 220, in wrapper
    response = callback(request, *args, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 460, in dispatch_detail
    return self.dispatch('detail', request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 483, in dispatch
    response = method(request, **kwargs)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 1362, in get_detail
    bundle = self.full_dehydrate(bundle)
  File "/usr/share/archivematica/virtualenvs/archivematica-storage-service/local/lib/python2.7/site-packages/tastypie/resources.py", line 893, in full_dehydrate
    bundle = self.dehydrate(bundle)
  File "/usr/lib/archivematica/storage-service/locations/api/resources.py", line 1314, in dehydrate
    bundle.data['result'] = bundle.obj.result
  File "/usr/lib/archivematica/storage-service/locations/models/async.py", line 36, in result
    return cPickle.loads(self._result)
TypeError: loads() argument 1 must be string, not buffer
```

This error was seen when Archivematica was trying to store an AIP. The logs in AM showed the following:

```
INTERNAL SERVER ERROR for url: http://localhost:8000/api/v2/async/5/
SIP creation failed.  See Storage Service logs for more details
500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:8000/api/v2/async/5/
storeAIP.py: WARNING   2018-05-16 00:06:07,056  archivematica.mcp.client.storeAIP:store_aip:184:  SIP unabled to be created: 500 Server Error: INTERNAL SERVER ERROR for url: http://localhost:8000/api/v2/async/5/.  See logs for more details.
```

**Comment by sevein** [comment]
I'm not sure how this wasn't detected before. It looks like Django could be returning a buffer/memoryview or bytes? See https://github.com/django/django/blob/stable/1.8.x/django/db/models/fields/__init__.py#L2331-L2371.

**Comment by nickwilkinson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Jisc RDSS](https://trello.com/c/LGTIS5UR/9-jisc-rdss)

**Comment by sevein** [comment]
For QA: I found this bug when processing one of the DSpace transfers found in https://github.com/artefactual/archivematica-sampledata/tree/master/SampleTransfers/DSpaceExport. If you can produce AIPs from those then I think this issue can be closed.

**Comment by sromkey** [comment]
Tested the DSpace sample and was able to create/store an AIP without issue.
