### ISSUE TITLE
Problem: package create async fails with authentication error

### ISSUE THREAD

**Issue by jrwdunham** [artefactual/archivematica-storage-service#381]
**Warning**: this may be an artifact of a fault in my dev system and not a true bug.

Bug seen on a SS qa/0.x (d59682011e193208e16faa0eaa14c0c57824d040) AM qa/1.x (e9f1e89277eac5489a9b3adccf2580236bda6aac) deploy.

The "Store the AIP" micro-service fails in its POST HTTP request to api/v2/file/async/ with this warning

    WARNING   2018-06-19 23:29:27,751  archivematica.mcp.client.storeAIP:store_aip:184:  SIP unabled to be created: 401 Client Error: UNAUTHORIZED for url: http://archivematica-storage-service:8000/api/v2/file/async/.  See logs for more details.

Debugging in SS `/locations/api/resources.py::Package.obj_create_async` indicates that the call to `bundle = super(PackageResource, self).obj_create(bundle, **kwargs)` raises `tastypie.exceptions.ImmediateHttpResponse`. The call chain goes to `self.authorized_create_detail(self.get_object_list(bundle.request), bundle)` which raises `Unauthorized` because `self._meta.authorization.create_detail(object_list, bundle)` returns `None`.

@ross-spencer was unable to re-create this issue.

**Comment by jrwdunham** [comment]
This may be related to the similar authentication error that is raised when I call `make bootstrap` in the Docker Compose deploy environment. The call to

    docker-compose run \
		--rm \
		--entrypoint /src/dashboard/src/manage.py \
			archivematica-dashboard \
				install \
					--username="test" \
					--password="test" \
					--email="test@test.com" \
					--org-name="test" \
					--org-id="test" \
					--api-key="test" \
					--ss-url="http://archivematica-storage-service:8000" \
					--ss-user="test" \
					--ss-api-key="test"

triggers this error

    archivematica.common:storageService:create_pipeline:107:  Creating pipeline in storage service with {'api_key': u'test', 'uuid': u'8eb5ee06-c39a-4180-8f42-fb9575d9f4e4', 'shared_path': '/var/archivematica/sharedDirectory/', 'api_username': u'test', 'create_default_locations': True, 'description': 'Archivematica on c38ce120ab79'}
    WARNING   2018-06-20 04:03:15  archivematica.common:storageService:create_pipeline:113:  Unable to create Archivematica pipeline in storage service from {'api_key': u'test', 'uuid': u'8eb5ee06-c39a-4180-8f42-fb9575d9f4e4', 'shared_path': '/var/archivematica/sharedDirectory/', 'api_username': u'test', 'create_default_locations': True, 'description': 'Archivematica on c38ce120ab79'} because 401 Client Error: UNAUTHORIZED for url: http://archivematica-storage-service:8000/api/v2/pipeline/
    Traceback (most recent call last):
      File "/src/archivematicaCommon/lib/storageService.py", line 111, in create_pipeline
        response.raise_for_status()
      File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    HTTPError: 401 Client Error: UNAUTHORIZED for url: http://archivematica-storage-service:8000/api/v2/pipeline/
    Traceback (most recent call last):
      File "/src/dashboard/src/manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
        output = self.handle(*args, **options)
      File "/src/dashboard/src/installer/management/commands/install.py", line 58, in handle
        setup_pipeline_in_ss(use_default_config=True)
      File "/src/dashboard/src/installer/steps.py", line 78, in setup_pipeline_in_ss
        api_key=api_key.key,
      File "/src/archivematicaCommon/lib/storageService.py", line 111, in create_pipeline
        response.raise_for_status()
      File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: http://archivematica-storage-service:8000/api/v2/pipeline/

despite the fact that a user with username `test` and API Key `test` was successfully created in the SS in a prior bootstrap step.

**Comment by jrwdunham** [comment]
To re-create:

1. Use the docker-compose deploy strategy to build an AM/SS instance using SS at qa/0.x (d596820) and AM at qa/1.x (e9f1e89277eac5489a9b3adccf2580236bda6aac).
2. Set the default processing config as in the screenshot below.
3. Initiate a transfer on TestTransfers/small/ of AM-sampledata.
4. Expect a failure in microservice **Store the AIP**.

<img width="1440" alt="ss-issue-381-processing-config-screenshot" src="https://user-images.githubusercontent.com/2504271/41637963-9222dcbe-740b-11e8-8dfe-30a35cf8cdbc.png">

**Comment by jrwdunham** [comment]
@sevein @ross-spencer It turns out that the true culprit was https://github.com/artefactual-labs/am/issues/56. The SS user created by the Docker Compose Makefile needs to be a superuser or else it lacks authorization to execute make state-changing API calls.
